Fix: "ERROR: Rebuilding xlogdb is not supported for servers using cloud storage" while not running `rebuild-xlogdb`
When running a command other than `rebuild-xlogdb` (e.g. `list-backups`) on
a new Barman server set specifically for restoring cloud backups, the
following error was being thrown:

```
    ERROR: Rebuilding xlogdb is not supported for servers using cloud storage
```

This happens because, being a new server that does not archive, the `xlog.db`
has not been created yet, so it tries try to run the `rebuild-xlogdb`
internally to create it and fail with that error message, even though
the command run by the user was not `rebuild-xlogdb` directly.

This commit fixes the issue by only displaying the error message when
`rebuild-xlogdb` is being run directly by the user
(i.e. when `silent` is `False` on `rebuild_xlogdb` method).

References: BAR-1243

Signed-off-by: Gustavo William <gustavo.oliveira@enterprisedb.com>