Fix: '<' not supported between instances of 'NoneType' and 'int'
When setting up a new Barman server for restoring existing backups from the
cloud, the following error was being raised when running `barman check`:

```
    TypeError: '<' not supported between instances of 'NoneType' and 'int'
```

The error was generated when trying to compare:

```
    if backup.size < last_backup_minimum_size:
```

But `backup.size` is None. This happens on the `validate_last_backup_min_size` method.

The code was instantiating a new `BackupInfo` object passing only the `backup_id`.
When doing this locally, it works because the `LocalBackupInfo` class
searches for the local file and loads it, so the object has all attributes.
However, for cloud backups, the code obviously does not fetch the file,
thus the object has most of its attributes as `None`.

This commit fixes the issue by, instead of instantiating a new `BackupInfo` object,
simply get the existing object from the backup cache using the existing `get_backup`
method.

Signed-off-by: Gustavo William <gustavo.oliveira@enterprisedb.com>

References: BAR-1252